function Configuracoes() {
	this.TAMANHO_CELULA = 70;
	this.TAMANHO_JOGADOR = (this.TAMANHO_CELULA / 4) - 3;

	this.DISTANCIA_MENU_TABULEIRO = 10;
	this.ALTURA_MENU = 50;
	this.LARGURA_MENU = 185;
	this.TEMPO_ANIMACAO_TURNO = 500;
	this.TEMPO_AVANCO_JOGADOR = 50;
	this.TAMANHO_TEXTO_CELULAS = '12px';
	this.TAMANHO_TEXTO_EVENTOS = '20px';
	this.TAMANHO_LINHA_RESPOSTAS = 10;

	this.LARGURA_TELA_PERGUNTAS = 500;
	this.TAMANHO_CIRCULO_RESPOSTAS = 8;
	this.LARGURA_TELA_FINAL_PERGUNTAS = 300;

	this.TAMANHO_QUADRADO_MONTAR_BLAH = 30;

	this.URL_SERVER = 'ws://localhost/Comunicacao'
}

var configuracoes = new Configuracoes();